### ISSUE TITLE
vakit verileri nasıl sağlanıyor

### ISSUE THREAD

**Issue by canbax** [ademilter/prayer-times#101]
Merhaba. Ben https://github.com/canbax/namaz-vakti-api nin geliştiricisiyim. Sadece merak ettiğimden soruyorum. Acaba verileri nasıl nereden çekiyorsunuz?

**Comment by ademilter** [comment]
https://ezanvakti.herokuapp.com kullanıyorum
@furkantektas sağolsun

**Comment by canbax** [comment]
hm anladım peki teşekkürler. Veriler nasıl hesaplanıyorsa diyanetin açık kaynaklı, ücretsiz bir yazılım ve API sunmasını beklerdim. Zamanında çok aradım fakat bulamadım. Öyle olunca iş başa düştü kendim yaptım :)
