### ISSUE TITLE
dil sorunu

### ISSUE THREAD

**Issue by ademilter** [ademilter/prayer-times#57]
"ana ekrana ekle"nen uygulamanın dili değiştirilse bile sayfa yenilendiğinde eskiye dönüyormuş.

**Comment by theilgaz** [comment]
## Resim 1
Dil Türkçe'ye çevirilip kaydedildikten sonra yeniden açarken dil telefon diline dönüyor, açıklama alanında vakit ismi Türkçe geliyor.

<img src="https://user-images.githubusercontent.com/13048645/223424673-839d5641-e9fb-4599-b94b-46d2325ea825.PNG" height="600" />

## Resim 2
App'i kapatmadan alt tarafta tutulduğu zaman dil Türkçe kalıyor.
<img src="https://user-images.githubusercontent.com/13048645/223424686-dffe24b0-3ab0-4701-a298-70ea550607fd.PNG" height="600" />
