### ISSUE TITLE
The source of the prayer times

### ISSUE THREAD

**Issue by emrergin** [ademilter/prayer-times#63]
I was pretty excited to see this project since I thought, Presidency of Religious Affairs finally released an API for their prayer times.

I checked to see whether the times given in this website are accurate according to them, but nope.

This issue is not about building an API where the Turkish government does not. But you may want to add a reminder for Turkish users, since there are discrepancies between the times shown here and the times announced by Diyanet.

In the case you need an accurate API, this is the best candidate I saw, https://abdus.dev/projects/prayertimes/ , although I did not check the times for it. He seems to suggest that he built the API based on Diyanet times, though.

**Comment by ademilter** [comment]
cc @furkantektas

**Comment by furkantektas** [comment]
👋 @emrergin any particular city and date for inaccurate times?

**Comment by furkantektas** [comment]
Also, Diyanet just provided an API for the first time two months ago: https://github.com/DinIsleriYuksekKurulu/AwqatSalah

However, the API is not public, the distribution of API credentials is prohibited, and Diyanet imposes a strict rate limit. With such constraints, there is no practical use of the service other than the smart screens in mosques.

**Comment by emrergin** [comment]
> 👋 @emrergin any particular city and date for inaccurate times?

Any city will do for Asr times. I checked it for Bolu.

**Comment by furkantektas** [comment]
It seems correct, are you sure you are looking at the Bolu city center on both?

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/1281777/224505772-22c58c37-50be-45ea-8299-485fe3038864.png">

**Comment by emrergin** [comment]
> It seems correct, are you sure you are looking at the Bolu city center on both?
> 
> <img alt="image" width="1182" src="https://user-images.githubusercontent.com/1281777/224505772-22c58c37-50be-45ea-8299-485fe3038864.png">

I am really sorry. I don't know what exactly did I do wrong, but the difference I remember was up to 1 hour, hence wanted to give a heads up.

Now that it seems that my false alarm was totally baseless, I will close this off. Really sorry for wasting everyone's time.

**Comment by furkantektas** [comment]
No problem, it's important to make sure the times are exactly the same :)
