### ISSUE TITLE
ayarlar sayfasındaki sürekli istek hakkında

### ISSUE THREAD

**Issue by enteresanlikk** [ademilter/prayer-times#64]
selam, ayarlar sayfasında işaretli butonlara her hover olduğumuzda json dosyalarına istek atılıyor. üst üste 10-15 defa hover olduğumda network, ekran görüntüsündeki hale geliyor. bir sorun olarak gördüm ancak başka bir açıklaması var mı? bilgilendirirseniz sevinirim.
![image](https://user-images.githubusercontent.com/23117378/224439482-705e09de-72d5-4da4-9c4e-ef92580d1db5.png)

**Comment by sinansonmez** [comment]
Next.js ile hiç çalışmamış olsam da, katkıda bulunmak için incelemek istedim. 

Network istegi atilan 3 nokta da NextJs' in `Link` componentini kullaniyor. Next.js dokümantasyonuna baktığımda, bu beklenen bir durum ve hover yapıldığında sayfaya gidileceğini düşünüyor ve sayfayi prefetch ediyor. `prefetch={false}` olsa bile hover da fetch etmeye devam ediyor.

https://nextjs.org/docs/api-reference/next/link

`
prefetch - Prefetch the page in the background. Defaults to true. Any <Link /> that is in the viewport (initially or through scroll) will be preloaded. Prefetch can be disabled by passing prefetch={false}. When prefetch is set to false, prefetching will still occur on hover. Pages using [Static Generation](https://nextjs.org/docs/basic-features/data-fetching/get-static-props) will preload JSON files with the data for faster page transitions. Prefetching is only enabled in production
`

**Comment by ademilter** [comment]
prefetch özelliğini kapatabilirim ama bu uygulama mobil ağırlıklı ve hover özelliği neredeyse kullanılmayacak gibi. bi sorun olmayacağını düşünerek böyle bırakıyorum. itirazı olan varssa tekrar tartışalım :)
