### ISSUE TITLE
Lokalizasyon dosyalarındaki bazı stil farklılıkları

### ISSUE THREAD

**Issue by ahmetcanaydemir** [ademilter/prayer-times#72]
Tablodaki lokalizasyon keyleri için stil farklılıkları bulunuyor. Eğer özellikle bu stiller seçilmediyse, daha tutarlı olması için her bir satırda ortak stil belirlenip uygulanabilir.

| key                     | tr                      | en                   |
|-------------------------|-------------------------|----------------------|
| settingsCurrentLocation | Mevcut **k**onum        | Current **L**ocation |
| settingsSelectCountry   | Bir **ü**lke **s**eçin  | Select a **C**ountry |
| settingsSelectRegion    | Bir **ş**ehir **s**eçin | Select a **R**egion  |
| settingsSelectCity      | Bir **i**lçe **s**eçin  | Select a **C**ity    |
| settingsNoAdjustments   | Ayar **Y**ok            | No **a**djustments   |

**Comment by ademilter** [comment]
bildirdiğin için teşekkürler ahmet, işi üzerime alıyorum 👍
