### ISSUE TITLE
Gece modunda bazı iconların pek belirli olmaması

### ISSUE THREAD

**Issue by alpererdogan8** [ademilter/prayer-times#79]
#### Denk geldiğim bir durumdu diğer iconlarda böyle bir sorun var mı emin değilim, güneş iconu kırmızı renkte bayağı bir silikti eğer bu bir sorun ise diye bildirmek istedim 🙂 
---
![ScreenShot](https://user-images.githubusercontent.com/19363785/227808041-d0334786-8234-42f7-a2e5-d4b54601f158.jpg)

**Comment by ademilter** [comment]
teşekkürler alperen, evet bir sorun olmuş. en kısa sürede düzeltirim
