### ISSUE TITLE
Eğer bir ülkenin tek regionu varsa bile tekrardan seçme zorunluluğu

### ISSUE THREAD

**Issue by ghost** [ademilter/prayer-times#80]
Çoğu ülkede tek region var ve ülkeyi seçince tekrardan region ekranında o tek regionu seçmek gerekiyor. Eğer ülkenin tek regionu varsa doğrudan şehirler ekranına geçebilir. Doğru yolun bu olduğuna emin olmasam da region.tsx dosyasında alttaki useeffecti kullandığımda tek region varsa doğrudan şehirler ekranına aktarabildim localimde. Buradaki sıkıntı şehir ekranındayken geri butonuna basıldığında region ekranına geldiği için bu useeffect yine çalışıyor ve tekrardan şehirler sayfasına gidiyor. Bu kısmı çözemedim. Şehir ekranında geri butonuna hızlı şekilde art arda 2 kere tıklarsam country ekranına dönüyor ama olması gereken tek tıklamada country ekranına atmalı.

```js
useEffect(() => {
    if (data.length == 1) {
      const region = data[0];
      _setSettings({ ..._settings, region });
      push("/settings/city");
    }
  }, [data]);
```

**Comment by ademilter** [comment]
merhaba, çok güzel düşünmüşsünüz bu kod üzerinden devam edicem 👍
