### ISSUE TITLE
should we use another api instead of ezanvakti

### ISSUE THREAD

**Issue by yasintz** [ademilter/prayer-times#87]
http://ezanvakti.herokuapp.com bazen cokuyor.

<img width="859" alt="Screenshot 2023-04-03 at 06 28 43" src="https://user-images.githubusercontent.com/36041339/229404871-ae6e7589-87fd-4a8b-ae53-a9f582379854.png">

**Comment by ademilter** [comment]
merhaba,
bu repo sadece uygulamanın arayüzünü kapsamakta, API tarafını bir arkadaş sağolsun bize açtı ve kullanıyoruz. bir nebze çökmelerin önüne geçmek için middleware (cache) yazdım. şimdilik sorun olmuyor gibi düşünüyorum
