### ISSUE TITLE
Geçen bir vaktin diğer gün için güncellenmesi

### ISSUE THREAD

**Issue by ismailarilik** [ademilter/prayer-times#94]
Bir vakit geçtiğinde diğer günün vakti ile güncellenmesi daha iyi olmaz mı? Mesela ben Perşembe akşamı öğle vaktine bakıyorsam, bu Cuma'nın vaktini öğrenmek istememden kaynaklıdır. Yatsı vaktinde de sabah vaktine bakıyorsam, ertesi günün sabah vaktini merak ediyorumdur. Bu konuda ne düşünüyorsunuz? @ademilter

**Comment by tolgahand** [comment]
Bence hem vakit kaybı hem de kafa karıştırıcı olur. Günler arasında zaten 1-2 dakika oynuyor.
Böyle bir özellik olsa ben kullanmazdım.

**Comment by ademilter** [comment]
@ismailarilik bahsettiğin değişiklik çok kafa karıştırır açıkcası. böyle kalmasını tercih ederim

**Comment by ismailarilik** [comment]
Peki, teşekkür ederim. Bu arada "Not planned" gibi bir nedenle de kapatılabiliyor issue'lar, biliyorsundur muhtemelen, bu issue için önemli de değil, söyleyeyim dedim sadece.
