### ISSUE TITLE
Namaz Kaza Takip Ozelligi

### ISSUE THREAD

**Issue by yasintz** [ademilter/prayer-times#96]
Acaba takip ozelligine ihtiyac duyuluyormudur? Tek sorun uygulamanin sadeligini bozarmi sorusu?

Ayrica, herhangi bir gelistirme ihtiyaci varsa (yoksa bile) dahil olmak isterim. react-native ile bir uygulama gelistirebiliriz cunku teknoloji ile icli disli olmayanlarin baktiklari ilk yer app/google store.

**Comment by ademilter** [comment]
@yasintz ilgin için teşekkür ederim. uygulamanın bu sadeliğini bozma niyetim yok :) hani olsa bile pwa sürümünde yapmak istemem. bu web'de çalışan yalın bir app olarak kalması güzel olur.

eğer bir şeye ihtiyaç olursa buraya task olarak mutlaka açarım 🙌
